/*
 * Copyright (c) 2020 Self-Order Kiosk
 */
package admin;

public class ItemsPanel extends javax.swing.JPanel {

  /**
   * Creates new form ItemsPanel
   */
  public ItemsPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    scpItems = new javax.swing.JScrollPane();
    tblItems = new javax.swing.JTable();
    pnlItemFields = new javax.swing.JPanel();
    lblItemImagePreview = new javax.swing.JLabel();
    lblItemName = new javax.swing.JLabel();
    lblItemPrice = new javax.swing.JLabel();
    lblItemImage = new javax.swing.JLabel();
    lblItemCategory = new javax.swing.JLabel();
    txtItemName = new javax.swing.JTextField();
    txtItemPrice = new javax.swing.JTextField();
    txtItemImage = new javax.swing.JTextField();
    cmbItemCategory = new javax.swing.JComboBox<>();
    pnlItemActions = new javax.swing.JPanel();
    btnItemRefresh = new javax.swing.JButton();
    btnItemSave = new javax.swing.JButton();
    btnItemNew = new javax.swing.JButton();
    btnItemDelete = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(720, 600));
    setLayout(new java.awt.GridBagLayout());

    tblItems.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"1", "Krabby Patty", "$ 1.99", "Meal Combos"}
      },
      new String [] {
        "ID", "Name", "Price", "Category"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblItems.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    scpItems.setViewportView(tblItems);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(scpItems, gridBagConstraints);

    java.awt.GridBagLayout pnlItemFieldsLayout = new java.awt.GridBagLayout();
    pnlItemFieldsLayout.columnWidths = new int[] {150, 100, 300};
    pnlItemFieldsLayout.rowHeights = new int[] {60, 0, 60};
    pnlItemFields.setLayout(pnlItemFieldsLayout);

    lblItemImagePreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblItemImagePreview.setText("Preview");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 5;
    gridBagConstraints.ipadx = 20;
    gridBagConstraints.ipady = 20;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    pnlItemFields.add(lblItemImagePreview, gridBagConstraints);

    lblItemName.setLabelFor(txtItemName);
    lblItemName.setText("Name");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlItemFields.add(lblItemName, gridBagConstraints);

    lblItemPrice.setLabelFor(txtItemPrice);
    lblItemPrice.setText("Price");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlItemFields.add(lblItemPrice, gridBagConstraints);

    lblItemImage.setLabelFor(txtItemImage);
    lblItemImage.setText("Image");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlItemFields.add(lblItemImage, gridBagConstraints);

    lblItemCategory.setLabelFor(cmbItemCategory);
    lblItemCategory.setText("Category");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlItemFields.add(lblItemCategory, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlItemFields.add(txtItemName, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlItemFields.add(txtItemPrice, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlItemFields.add(txtItemImage, gridBagConstraints);

    cmbItemCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main Meal" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlItemFields.add(cmbItemCategory, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(pnlItemFields, gridBagConstraints);

    pnlItemActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

    btnItemRefresh.setText("Refresh");
    pnlItemActions.add(btnItemRefresh);

    btnItemSave.setText("Save");
    pnlItemActions.add(btnItemSave);

    btnItemNew.setText("New");
    pnlItemActions.add(btnItemNew);

    btnItemDelete.setText("Delete");
    pnlItemActions.add(btnItemDelete);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
    add(pnlItemActions, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnItemDelete;
  private javax.swing.JButton btnItemNew;
  private javax.swing.JButton btnItemRefresh;
  private javax.swing.JButton btnItemSave;
  private javax.swing.JComboBox<String> cmbItemCategory;
  private javax.swing.JLabel lblItemCategory;
  private javax.swing.JLabel lblItemImage;
  private javax.swing.JLabel lblItemImagePreview;
  private javax.swing.JLabel lblItemName;
  private javax.swing.JLabel lblItemPrice;
  private javax.swing.JPanel pnlItemActions;
  private javax.swing.JPanel pnlItemFields;
  private javax.swing.JScrollPane scpItems;
  private javax.swing.JTable tblItems;
  private javax.swing.JTextField txtItemImage;
  private javax.swing.JTextField txtItemName;
  private javax.swing.JTextField txtItemPrice;
  // End of variables declaration//GEN-END:variables
}
