/*
 * Copyright (c) 2020 Self-Order Kiosk
 */
package admin;

public class OrdersPanel extends javax.swing.JPanel {

  /**
   * Creates new form OrdersPanel
   */
  public OrdersPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scpOrders = new javax.swing.JScrollPane();
    tblOrders = new javax.swing.JTable();

    setPreferredSize(new java.awt.Dimension(720, 600));
    setLayout(new java.awt.BorderLayout());

    tblOrders.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"1", "Pending", "2020-09-29"}
      },
      new String [] {
        "ID", "Status", "Date"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scpOrders.setViewportView(tblOrders);

    add(scpOrders, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane scpOrders;
  private javax.swing.JTable tblOrders;
  // End of variables declaration//GEN-END:variables
}
