/*
 * Copyright (c) 2020 Self-Order Kiosk
 */
package admin;

public class UsersPanel extends javax.swing.JPanel {

  /**
   * Creates new form UsersPanel
   */
  public UsersPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    scpUsers = new javax.swing.JScrollPane();
    tblUsers = new javax.swing.JTable();
    pnlUserFields = new javax.swing.JPanel();
    lblUserName = new javax.swing.JLabel();
    lblUserUsername = new javax.swing.JLabel();
    lblUserPassword = new javax.swing.JLabel();
    txtUserName = new javax.swing.JTextField();
    txtUserUsername = new javax.swing.JTextField();
    txtUserPassword = new javax.swing.JTextField();
    pnlUserActions = new javax.swing.JPanel();
    btnUserRefresh = new javax.swing.JButton();
    btnUserSave = new javax.swing.JButton();
    btnUserNew = new javax.swing.JButton();
    btnUserDelete = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(720, 600));
    setLayout(new java.awt.GridBagLayout());

    tblUsers.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"1", "SpongeBob SquarePants", "bob"}
      },
      new String [] {
        "ID", "Name", "Username"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scpUsers.setViewportView(tblUsers);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(scpUsers, gridBagConstraints);

    java.awt.GridBagLayout pnlUserFieldsLayout = new java.awt.GridBagLayout();
    pnlUserFieldsLayout.columnWidths = new int[] {100, 300};
    pnlUserFieldsLayout.rowHeights = new int[] {60, 0, 60};
    pnlUserFields.setLayout(pnlUserFieldsLayout);

    lblUserName.setLabelFor(txtUserName);
    lblUserName.setText("Name");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlUserFields.add(lblUserName, gridBagConstraints);

    lblUserUsername.setLabelFor(txtUserUsername);
    lblUserUsername.setText("Username");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlUserFields.add(lblUserUsername, gridBagConstraints);

    lblUserPassword.setLabelFor(txtUserPassword);
    lblUserPassword.setText("Password");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlUserFields.add(lblUserPassword, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlUserFields.add(txtUserName, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlUserFields.add(txtUserUsername, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlUserFields.add(txtUserPassword, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    add(pnlUserFields, gridBagConstraints);

    pnlUserActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

    btnUserRefresh.setText("Refresh");
    pnlUserActions.add(btnUserRefresh);

    btnUserSave.setText("Save");
    pnlUserActions.add(btnUserSave);

    btnUserNew.setText("New");
    pnlUserActions.add(btnUserNew);

    btnUserDelete.setText("Delete");
    pnlUserActions.add(btnUserDelete);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    add(pnlUserActions, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnUserDelete;
  private javax.swing.JButton btnUserNew;
  private javax.swing.JButton btnUserRefresh;
  private javax.swing.JButton btnUserSave;
  private javax.swing.JLabel lblUserName;
  private javax.swing.JLabel lblUserPassword;
  private javax.swing.JLabel lblUserUsername;
  private javax.swing.JPanel pnlUserActions;
  private javax.swing.JPanel pnlUserFields;
  private javax.swing.JScrollPane scpUsers;
  private javax.swing.JTable tblUsers;
  private javax.swing.JTextField txtUserName;
  private javax.swing.JTextField txtUserPassword;
  private javax.swing.JTextField txtUserUsername;
  // End of variables declaration//GEN-END:variables
}
