/*
 * Copyright (c) 2020 Self-Order Kiosk
 */
package app;

public class LaunchFrame extends javax.swing.JFrame {

  /**
   * Creates new form Splash
   */
  public LaunchFrame() {
    initComponents();
    app.Global.setAppIcon(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    pnlContainer = new javax.swing.JPanel();
    lblLogo = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    pnlActions = new javax.swing.JPanel();
    btnLaunchKiosk = new javax.swing.JButton();
    btnLaunchAdmin = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Launcher");
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(720, 600));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    pnlContainer.setMaximumSize(new java.awt.Dimension(640, 480));
    pnlContainer.setMinimumSize(new java.awt.Dimension(640, 480));
    pnlContainer.setPreferredSize(new java.awt.Dimension(640, 480));
    pnlContainer.setLayout(new java.awt.GridBagLayout());

    lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/app-logo-1x.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    pnlContainer.add(lblLogo, gridBagConstraints);

    lblTitle.setFont(lblTitle.getFont().deriveFont(lblTitle.getFont().getSize()+13f));
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("app/global"); // NOI18N
    lblTitle.setText(bundle.getString("appTitle")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.insets = new java.awt.Insets(20, 0, 50, 0);
    pnlContainer.add(lblTitle, gridBagConstraints);

    pnlActions.setMaximumSize(null);
    pnlActions.setPreferredSize(new java.awt.Dimension(420, 180));
    pnlActions.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

    btnLaunchKiosk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/water-heater.png"))); // NOI18N
    btnLaunchKiosk.setText("Launch Kiosk");
    btnLaunchKiosk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnLaunchKiosk.setIconTextGap(20);
    btnLaunchKiosk.setPreferredSize(new java.awt.Dimension(300, 400));
    btnLaunchKiosk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnLaunchKiosk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLaunchKioskActionPerformed(evt);
      }
    });
    pnlActions.add(btnLaunchKiosk);

    btnLaunchAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/online-test.png"))); // NOI18N
    btnLaunchAdmin.setText("Launch Admin");
    btnLaunchAdmin.setToolTipText("");
    btnLaunchAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnLaunchAdmin.setIconTextGap(20);
    btnLaunchAdmin.setPreferredSize(new java.awt.Dimension(300, 400));
    btnLaunchAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnLaunchAdmin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLaunchAdminActionPerformed(evt);
      }
    });
    pnlActions.add(btnLaunchAdmin);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    pnlContainer.add(pnlActions, gridBagConstraints);

    getContentPane().add(pnlContainer, new java.awt.GridBagConstraints());

    getAccessibleContext().setAccessibleName("");

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLaunchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchAdminActionPerformed
    new admin.LoginFrame().setVisible(true);

    // Minimize the LaunchFrame frame
    // setState(javax.swing.JFrame.ICONIFIED);
  }//GEN-LAST:event_btnLaunchAdminActionPerformed

  private void btnLaunchKioskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchKioskActionPerformed
    new kiosk.StartFrame().setVisible(true);

    // Minimize the LaunchFrame frame
    // setState(javax.swing.JFrame.ICONIFIED);
  }//GEN-LAST:event_btnLaunchKioskActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set default theme */
    app.Global.setDefaultTheme();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new LaunchFrame().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLaunchAdmin;
  private javax.swing.JButton btnLaunchKiosk;
  private javax.swing.JLabel lblLogo;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JPanel pnlActions;
  private javax.swing.JPanel pnlContainer;
  // End of variables declaration//GEN-END:variables
}
