/*
 * Copyright (c) 2020 Self-Order Kiosk
 */
package app;

public class SplashGradientPanel extends javax.swing.JPanel {

  /**
   * Creates new form SplashGradientPanel
   */
  public SplashGradientPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lblLogo = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/app-symbol.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 30;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    add(lblLogo, gridBagConstraints);

    lblTitle.setFont(new java.awt.Font("Arial", 1, 37)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(255, 255, 255));
    lblTitle.setText("<html>Self-Order<br/>Kiosk</html>");
    lblTitle.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    add(lblTitle, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  @Override
  protected void paintComponent(java.awt.Graphics g) {
    super.paintComponent(g);
    java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
    g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
    int w = getWidth();
    int h = getHeight();
    java.awt.Color color1 = java.awt.Color.decode(java.util.ResourceBundle.getBundle("app/global").getString("colorPrimaryAlt"));
    java.awt.Color color2 = java.awt.Color.decode(java.util.ResourceBundle.getBundle("app/global").getString("colorPrimary"));
    java.awt.GradientPaint gp = new java.awt.GradientPaint(0, 0, color1, 0, h, color2);
    g2d.setPaint(gp);
    g2d.fillRect(0, 0, w, h);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lblLogo;
  private javax.swing.JLabel lblTitle;
  // End of variables declaration//GEN-END:variables
}
