package kiosk;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Hassen
 */
public class CustomizeOrderFrame extends javax.swing.JFrame implements Observable {

  /**
   * Creates new form CustomizeOrder
   */
  public CustomizeOrderFrame() {
    initComponents();

  }
  float CustomPrice = 50;

  public CustomizeOrderFrame(String OrderName, float price) {
    initComponents();
    OrderNameLabel.setText(OrderName);
    CustomPrice = price;
    TotalValue.setText("" + CustomPrice);

  }
  ArrayList<Observer> obs = new ArrayList();

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("serial")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    OrderNameLabel = new javax.swing.JLabel();
    CustomizeOrder = new javax.swing.JPanel();
    SizeLabel = new javax.swing.JLabel();
    btnSmall = new javax.swing.JButton();
    btnMedium = new javax.swing.JButton();
    btnLarge = new javax.swing.JButton();
    QuantityPanel = new javax.swing.JPanel();
    QuantityLabel = new javax.swing.JLabel();
    IncrementQuntity = new javax.swing.JButton();
    DecrementQuntity1 = new javax.swing.JButton();
    DisplayQuantity = new javax.swing.JTextField();
    TotalValue = new javax.swing.JLabel();
    DollarSign = new javax.swing.JLabel();
    TotalLabel = new javax.swing.JLabel();
    ActionButtons = new javax.swing.JPanel();
    btnCancel = new javax.swing.JButton();
    btnAddToOrder = new javax.swing.JButton();
    TitleSeparator = new javax.swing.JSeparator();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Customize Item");

    Main.setBackground(new java.awt.Color(255, 255, 255));

    OrderNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    OrderNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    OrderNameLabel.setText("Combo burger 1");

    CustomizeOrder.setBackground(new java.awt.Color(255, 255, 255));

    SizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
    SizeLabel.setText("Size");

    btnSmall.setBackground(new java.awt.Color(255, 255, 255));
    btnSmall.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    btnSmall.setText("SMALL");
    btnSmall.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSmallActionPerformed(evt);
      }
    });

    btnMedium.setBackground(new java.awt.Color(255, 255, 255));
    btnMedium.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    btnMedium.setText("MEDIUM");
    btnMedium.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnMediumActionPerformed(evt);
      }
    });

    btnLarge.setBackground(new java.awt.Color(255, 255, 255));
    btnLarge.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    btnLarge.setText("LARGE");
    btnLarge.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLargeActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout CustomizeOrderLayout = new javax.swing.GroupLayout(CustomizeOrder);
    CustomizeOrder.setLayout(CustomizeOrderLayout);
    CustomizeOrderLayout.setHorizontalGroup(
      CustomizeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(CustomizeOrderLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(SizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(253, 253, 253)
        .addComponent(btnSmall, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 166, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(btnLarge, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(47, 47, 47))
    );
    CustomizeOrderLayout.setVerticalGroup(
      CustomizeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(CustomizeOrderLayout.createSequentialGroup()
        .addGap(97, 97, 97)
        .addGroup(CustomizeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(SizeLabel))
        .addContainerGap(132, Short.MAX_VALUE))
    );

    QuantityPanel.setBackground(new java.awt.Color(255, 255, 255));

    QuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    QuantityLabel.setText("Quantity");

    IncrementQuntity.setBackground(new java.awt.Color(12, 154, 119));
    IncrementQuntity.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    IncrementQuntity.setForeground(new java.awt.Color(255, 255, 255));
    IncrementQuntity.setText("+");
    IncrementQuntity.setAlignmentY(0.0F);
    IncrementQuntity.setMaximumSize(new java.awt.Dimension(59, 59));
    IncrementQuntity.setMinimumSize(new java.awt.Dimension(59, 59));
    IncrementQuntity.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IncrementQuntityActionPerformed(evt);
      }
    });

    DecrementQuntity1.setBackground(new java.awt.Color(12, 154, 119));
    DecrementQuntity1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    DecrementQuntity1.setForeground(new java.awt.Color(255, 255, 255));
    DecrementQuntity1.setText("-");
    DecrementQuntity1.setAlignmentY(0.0F);
    DecrementQuntity1.setMaximumSize(new java.awt.Dimension(59, 59));
    DecrementQuntity1.setMinimumSize(new java.awt.Dimension(59, 59));
    DecrementQuntity1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DecrementQuntity1ActionPerformed(evt);
      }
    });

    DisplayQuantity.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
    DisplayQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    DisplayQuantity.setText("1");

    TotalValue.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    TotalValue.setText("60.00");

    DollarSign.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    DollarSign.setText("$");

    TotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    TotalLabel.setText("Total:");

    javax.swing.GroupLayout QuantityPanelLayout = new javax.swing.GroupLayout(QuantityPanel);
    QuantityPanel.setLayout(QuantityPanelLayout);
    QuantityPanelLayout.setHorizontalGroup(
      QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(QuantityPanelLayout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(QuantityPanelLayout.createSequentialGroup()
            .addComponent(QuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(773, Short.MAX_VALUE))
          .addGroup(QuantityPanelLayout.createSequentialGroup()
            .addComponent(DecrementQuntity1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(DisplayQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(IncrementQuntity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TotalLabel)
            .addGap(47, 47, 47)
            .addComponent(DollarSign)
            .addGap(18, 18, 18)
            .addComponent(TotalValue)
            .addGap(57, 57, 57))))
    );
    QuantityPanelLayout.setVerticalGroup(
      QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuantityPanelLayout.createSequentialGroup()
        .addContainerGap(60, Short.MAX_VALUE)
        .addComponent(QuantityLabel)
        .addGroup(QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(QuantityPanelLayout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addGroup(QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(DisplayQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(DecrementQuntity1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(IncrementQuntity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(109, 109, 109))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuantityPanelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(QuantityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(TotalValue)
              .addComponent(TotalLabel)
              .addComponent(DollarSign))
            .addGap(111, 111, 111))))
    );

    ActionButtons.setBackground(new java.awt.Color(255, 255, 255));

    btnCancel.setBackground(new java.awt.Color(0, 0, 0));
    btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnCancel.setForeground(new java.awt.Color(255, 255, 255));
    btnCancel.setText("CANCEL");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    btnAddToOrder.setBackground(new java.awt.Color(0, 0, 0));
    btnAddToOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnAddToOrder.setForeground(new java.awt.Color(255, 255, 255));
    btnAddToOrder.setText("ADD TO ORDER");
    btnAddToOrder.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddToOrderActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ActionButtonsLayout = new javax.swing.GroupLayout(ActionButtons);
    ActionButtons.setLayout(ActionButtonsLayout);
    ActionButtonsLayout.setHorizontalGroup(
      ActionButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ActionButtonsLayout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnAddToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(52, 52, 52))
    );
    ActionButtonsLayout.setVerticalGroup(
      ActionButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ActionButtonsLayout.createSequentialGroup()
        .addGroup(ActionButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAddToOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(CustomizeOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(QuantityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(ActionButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(MainLayout.createSequentialGroup()
            .addComponent(TitleSeparator)
            .addGap(89, 89, 89))
          .addComponent(OrderNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addComponent(OrderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(TitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(17, 17, 17)
        .addComponent(CustomizeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(QuantityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ActionButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  int Quantity = 1;
  String OrderSize = "";
  String Spicy = "";

  float CustomTotal = CustomPrice;


  private void IncrementQuntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncrementQuntityActionPerformed
    Quantity++;
    DisplayQuantity.setText("" + Quantity);
    CustomPrice = Quantity * CustomPrice;
    TotalValue.setText("" + CustomTotal);
  }//GEN-LAST:event_IncrementQuntityActionPerformed

  private void DecrementQuntity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecrementQuntity1ActionPerformed
    if (Quantity == 1) {
    } else {
      Quantity--;
      DisplayQuantity.setText("" + Quantity);
      CustomPrice = Quantity * CustomPrice;
      TotalValue.setText("" + CustomTotal);
    }
  }//GEN-LAST:event_DecrementQuntity1ActionPerformed

  private void btnSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallActionPerformed
    OrderSize = "Small";
    CustomPrice = CustomPrice + getSizeFee();
    TotalValue.setText("" + CustomPrice);
    ClickColorSwitch(btnSmall, btnMedium, btnLarge);

  }//GEN-LAST:event_btnSmallActionPerformed

  private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
    OrderSize = "Medium";
    CustomPrice = CustomPrice + getSizeFee();
    TotalValue.setText("" + CustomPrice);
//   TODO make a function for changing the price
    ClickColorSwitch(btnMedium, btnSmall, btnLarge);
  }//GEN-LAST:event_btnMediumActionPerformed

  private void btnLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLargeActionPerformed
    OrderSize = "Large";
    CustomPrice = CustomPrice + getSizeFee();
    TotalValue.setText("" + CustomPrice);
    ClickColorSwitch(btnLarge, btnMedium, btnSmall);

  }//GEN-LAST:event_btnLargeActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToOrderActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnAddToOrderActionPerformed

  public void ClickColorSwitch(JButton b1, JButton b2, JButton b3) {
    b1.setBackground(new Color(12, 154, 119));
    b1.setForeground(new Color(255, 255, 255));
    btnlight(b2);
    btnlight(b3);
  }

  public void btnlight(JButton b2) {
    b2.setBackground(new Color(255, 255, 255));
    b2.setForeground(new Color(0, 0, 0));
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CustomizeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CustomizeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CustomizeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CustomizeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CustomizeOrderFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ActionButtons;
  private javax.swing.JPanel CustomizeOrder;
  private javax.swing.JButton DecrementQuntity1;
  private javax.swing.JTextField DisplayQuantity;
  private javax.swing.JLabel DollarSign;
  private javax.swing.JButton IncrementQuntity;
  private javax.swing.JPanel Main;
  private javax.swing.JLabel OrderNameLabel;
  private javax.swing.JLabel QuantityLabel;
  private javax.swing.JPanel QuantityPanel;
  private javax.swing.JLabel SizeLabel;
  private javax.swing.JSeparator TitleSeparator;
  private javax.swing.JLabel TotalLabel;
  private javax.swing.JLabel TotalValue;
  private javax.swing.JButton btnAddToOrder;
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnLarge;
  private javax.swing.JButton btnMedium;
  private javax.swing.JButton btnSmall;
  // End of variables declaration//GEN-END:variables

  float getSizeFee() {
    switch (OrderSize) {
      case "Small":
        return -10;
      case "Large":
        return 20;
      default:
        return 0;
    }

  }

  @Override
  public void addObserver(Observer observer) {
    obs.add(observer);
  }
}
