package kiosk;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Hassen
 */
public class EatingLocationFrame extends javax.swing.JFrame {

  /**
   * Creates new form EatingLocationScreen
   */
  public EatingLocationFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    lblWhereToEat = new javax.swing.JLabel();
    TitleSeparator = new javax.swing.JSeparator();
    btnBack = new javax.swing.JButton();
    btnNext = new javax.swing.JButton();
    Locations = new javax.swing.JPanel();
    btnDineIn = new javax.swing.JButton();
    btnTakeOut = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    Main.setBackground(new java.awt.Color(255, 255, 255));
    Main.setPreferredSize(new java.awt.Dimension(1048, 1000));

    lblWhereToEat.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    lblWhereToEat.setText("Where do you want to eat?");

    TitleSeparator.setBackground(new java.awt.Color(0, 51, 51));
    TitleSeparator.setForeground(new java.awt.Color(12, 154, 119));

    btnBack.setBackground(new java.awt.Color(0, 0, 0));
    btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnBack.setForeground(new java.awt.Color(255, 255, 255));
    btnBack.setText("BACK");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBackActionPerformed(evt);
      }
    });

    btnNext.setBackground(new java.awt.Color(0, 0, 0));
    btnNext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnNext.setForeground(new java.awt.Color(255, 255, 255));
    btnNext.setText("NEXT");
    btnNext.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNextActionPerformed(evt);
      }
    });

    Locations.setBackground(new java.awt.Color(255, 255, 255));
    Locations.setPreferredSize(new java.awt.Dimension(922, 500));

    btnDineIn.setBackground(new java.awt.Color(255, 255, 255));
    btnDineIn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    btnDineIn.setText("DINE IN");
    btnDineIn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDineInActionPerformed(evt);
      }
    });

    btnTakeOut.setBackground(new java.awt.Color(255, 255, 255));
    btnTakeOut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    btnTakeOut.setText("TAKE OUT");
    btnTakeOut.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTakeOutActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout LocationsLayout = new javax.swing.GroupLayout(Locations);
    Locations.setLayout(LocationsLayout);
    LocationsLayout.setHorizontalGroup(
      LocationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LocationsLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(btnDineIn, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        .addGap(37, 37, 37)
        .addComponent(btnTakeOut, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        .addGap(38, 38, 38))
    );
    LocationsLayout.setVerticalGroup(
      LocationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LocationsLayout.createSequentialGroup()
        .addGap(67, 67, 67)
        .addGroup(LocationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnDineIn, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
          .addComponent(btnTakeOut, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        .addGap(206, 206, 206))
    );

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addGap(69, 69, 69)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(Locations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(TitleSeparator, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
            .addComponent(lblWhereToEat, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(MainLayout.createSequentialGroup()
            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(8, 8, 8)))
        .addGap(57, 57, 57))
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addComponent(lblWhereToEat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(TitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(Locations, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    OrderSummaryFrame obj = new OrderSummaryFrame();
    obj.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnBackActionPerformed

  private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    PaymentMethodFrame obj = new PaymentMethodFrame();
    obj.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnNextActionPerformed

  private void btnDineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDineInActionPerformed
    ClickColorSwitch(btnDineIn, btnTakeOut);
  }//GEN-LAST:event_btnDineInActionPerformed

  private void btnTakeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeOutActionPerformed
    ClickColorSwitch(btnTakeOut, btnDineIn);
  }//GEN-LAST:event_btnTakeOutActionPerformed

  public void ClickColorSwitch(JButton b1, JButton b2) {
    b1.setBackground(new Color(12, 154, 119));
    b1.setForeground(new Color(255, 255, 255));
    btnlight(b2);
  }

  public void btnlight(JButton b2) {
    b2.setBackground(new Color(255, 255, 255));
    b2.setForeground(new Color(0, 0, 0));
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EatingLocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EatingLocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EatingLocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EatingLocationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new EatingLocationFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Locations;
  private javax.swing.JPanel Main;
  private javax.swing.JSeparator TitleSeparator;
  private javax.swing.JButton btnBack;
  private javax.swing.JButton btnDineIn;
  private javax.swing.JButton btnNext;
  private javax.swing.JButton btnTakeOut;
  private javax.swing.JLabel lblWhereToEat;
  // End of variables declaration//GEN-END:variables
}
