package kiosk;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Hassen
 */
public class EndFrame extends javax.swing.JFrame {

  /**
   * Creates new form EatingLocationScreen
   */
  public EndFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    Main = new javax.swing.JPanel();
    lblWhereToEat = new javax.swing.JLabel();
    TitleSeparator = new javax.swing.JSeparator();
    Display = new javax.swing.JPanel();
    lbl = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    SmileyLogo = new javax.swing.JLabel();
    ActionButtons = new javax.swing.JPanel();
    btnFinish = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    Main.setBackground(new java.awt.Color(255, 255, 255));
    Main.setPreferredSize(new java.awt.Dimension(1048, 1000));

    lblWhereToEat.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    lblWhereToEat.setText("Done");

    TitleSeparator.setBackground(new java.awt.Color(0, 51, 51));
    TitleSeparator.setForeground(new java.awt.Color(12, 154, 119));

    Display.setBackground(new java.awt.Color(255, 255, 255));
    Display.setPreferredSize(new java.awt.Dimension(922, 500));

    lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl.setText("Your order is being prepared");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Please wait until its complete");

    SmileyLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    SmileyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simley.png"))); // NOI18N

    javax.swing.GroupLayout DisplayLayout = new javax.swing.GroupLayout(Display);
    Display.setLayout(DisplayLayout);
    DisplayLayout.setHorizontalGroup(
      DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(DisplayLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addComponent(SmileyLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    DisplayLayout.setVerticalGroup(
      DisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayLayout.createSequentialGroup()
        .addComponent(SmileyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
        .addComponent(lbl)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addContainerGap())
    );

    ActionButtons.setBackground(new java.awt.Color(255, 255, 255));
    ActionButtons.setLayout(new java.awt.GridBagLayout());

    btnFinish.setBackground(new java.awt.Color(0, 0, 0));
    btnFinish.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnFinish.setForeground(new java.awt.Color(255, 255, 255));
    btnFinish.setText("FINISH");
    btnFinish.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFinishActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 191;
    gridBagConstraints.ipady = 29;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 380, 15, 381);
    ActionButtons.add(btnFinish, gridBagConstraints);

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
        .addGap(69, 69, 69)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
          .addComponent(TitleSeparator, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
            .addComponent(lblWhereToEat, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addGap(57, 57, 57))
      .addComponent(ActionButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addComponent(lblWhereToEat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(TitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(43, 43, 43)
        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(ActionButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
    new StartFrame().setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnFinishActionPerformed

  public void ClickColorSwitch(JButton b1, JButton b2) {
    b1.setBackground(new Color(12, 154, 119));
    b1.setForeground(new Color(255, 255, 255));
    btnlight(b2);
  }

  public void btnlight(JButton b2) {
    b2.setBackground(new Color(255, 255, 255));
    b2.setForeground(new Color(0, 0, 0));
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EndFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new EndFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ActionButtons;
  private javax.swing.JPanel Display;
  private javax.swing.JPanel Main;
  private javax.swing.JLabel SmileyLogo;
  private javax.swing.JSeparator TitleSeparator;
  private javax.swing.JButton btnFinish;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lbl;
  private javax.swing.JLabel lblWhereToEat;
  // End of variables declaration//GEN-END:variables
}
