package kiosk;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hassen
 */
public class OrderSummaryFrame extends javax.swing.JFrame {

  /**
   * Creates new form OrderSummary
   */
  public OrderSummaryFrame() {
    initComponents();
    this.setTitle("Order Summary");
    String it1[] = {"1x Combo Spicy Meal (Large)", "15.00"};
    DefaultTableModel tblmodel = (DefaultTableModel) tblOrderDetails.getModel();
    tblmodel.addRow(it1);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    lblOrderSummary = new javax.swing.JLabel();
    TableScrollPane = new javax.swing.JScrollPane();
    tblOrderDetails = new javax.swing.JTable();
    TitleSeparator = new javax.swing.JSeparator();
    btnBack = new javax.swing.JButton();
    btnCheckout = new javax.swing.JButton();
    TotalLabel = new javax.swing.JLabel();
    DollarSign = new javax.swing.JLabel();
    TotalValue = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    Main.setBackground(new java.awt.Color(255, 255, 255));

    lblOrderSummary.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    lblOrderSummary.setText("Order Summary");

    TableScrollPane.getViewport().setBackground(new Color(255,255,255));
    TableScrollPane.setBackground(new java.awt.Color(255, 255, 255));

    tblOrderDetails.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
    tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Order", "Price"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblOrderDetails.setFillsViewportHeight(true);
    tblOrderDetails.setGridColor(new java.awt.Color(255, 255, 255));
    tblOrderDetails.setOpaque(false);
    tblOrderDetails.setRowHeight(80);
    tblOrderDetails.setTableHeader(null);
    TableScrollPane.setViewportView(tblOrderDetails);

    TitleSeparator.setBackground(new java.awt.Color(0, 51, 51));
    TitleSeparator.setForeground(new java.awt.Color(12, 154, 119));

    btnBack.setBackground(new java.awt.Color(0, 0, 0));
    btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnBack.setForeground(new java.awt.Color(255, 255, 255));
    btnBack.setText("BACK");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBackActionPerformed(evt);
      }
    });

    btnCheckout.setBackground(new java.awt.Color(0, 0, 0));
    btnCheckout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
    btnCheckout.setText("CHECKOUT");
    btnCheckout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCheckoutActionPerformed(evt);
      }
    });

    TotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    TotalLabel.setText("Total:");

    DollarSign.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    DollarSign.setText("$");

    TotalValue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    TotalValue.setText("60.00");

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblOrderSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(TitleSeparator, javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(TableScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(MainLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(TotalLabel)
            .addGap(18, 18, 18)
            .addComponent(DollarSign)
            .addGap(18, 18, 18)
            .addComponent(TotalValue))
          .addGroup(MainLayout.createSequentialGroup()
            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
            .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(44, 44, 44))
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addComponent(lblOrderSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(TitleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(TableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(TotalValue)
          .addComponent(TotalLabel)
          .addComponent(DollarSign))
        .addGap(82, 82, 82)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(19, 19, 19))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    MenuFrame obj = new MenuFrame();
    obj.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnBackActionPerformed

  private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
    EatingLocationFrame obj = new EatingLocationFrame();
    obj.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnCheckoutActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(OrderSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(OrderSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(OrderSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(OrderSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new OrderSummaryFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel DollarSign;
  private javax.swing.JPanel Main;
  private javax.swing.JScrollPane TableScrollPane;
  private javax.swing.JSeparator TitleSeparator;
  private javax.swing.JLabel TotalLabel;
  private javax.swing.JLabel TotalValue;
  private javax.swing.JButton btnBack;
  private javax.swing.JButton btnCheckout;
  private javax.swing.JLabel lblOrderSummary;
  private javax.swing.JTable tblOrderDetails;
  // End of variables declaration//GEN-END:variables
}
