package kiosk;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Hassen
 */
public class StartFrame extends javax.swing.JFrame {

  /**
   * Creates new form StartScreen
   */
  public StartFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    lblLogo = new javax.swing.JLabel();
    lblFastFood = new javax.swing.JLabel();
    actionButton = new javax.swing.JPanel();
    orderButton = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setSize(new java.awt.Dimension(970, 970));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    Main.setBackground(new java.awt.Color(255, 255, 255));
    Main.setBorder(new javax.swing.border.MatteBorder(null));

    lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-1x.png"))); // NOI18N

    lblFastFood.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
    lblFastFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblFastFood.setText("Fast Food");

    actionButton.setOpaque(false);
    actionButton.setLayout(new java.awt.GridBagLayout());

    orderButton.setBackground(new java.awt.Color(0, 0, 0));
    orderButton.setFont(new java.awt.Font("Segoe UI", 1, 62)); // NOI18N
    orderButton.setForeground(new java.awt.Color(255, 255, 255));
    orderButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    orderButton.setText("ORDER NOW");
    orderButton.setToolTipText("Click to start your order ");
    orderButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    orderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    orderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    orderButton.setIconTextGap(0);
    orderButton.setOpaque(true);
    orderButton.setPreferredSize(new java.awt.Dimension(490, 90));
    orderButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        orderButtonMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        orderButtonMouseExited(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        orderButtonMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        orderButtonMouseReleased(evt);
      }
    });
    actionButton.add(orderButton, new java.awt.GridBagConstraints());

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(actionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
      .addGroup(MainLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblFastFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE))
        .addContainerGap())
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addGap(117, 117, 117)
        .addComponent(lblFastFood)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
        .addComponent(lblLogo)
        .addGap(70, 70, 70)
        .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void orderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseEntered
    setcolor(orderButton);
  }//GEN-LAST:event_orderButtonMouseEntered

  private void orderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseExited
    resetcolor(orderButton);
  }//GEN-LAST:event_orderButtonMouseExited

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//    for(double i=0.0;i<=1.0;i=i+0.1){
//      float f= (float)i;
//      this.setOpacity(f);
//        try {
//            Thread.sleep(50);
//        
//      } catch (Exception e)
//      {
//      }
//    }
  }//GEN-LAST:event_formWindowOpened

  private void orderButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMousePressed
    orderButton.setBackground(new Color(12, 154, 119));
  }//GEN-LAST:event_orderButtonMousePressed

  private void orderButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseReleased
    MenuFrame menu = new MenuFrame();
    menu.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_orderButtonMouseReleased
  void setcolor(JLabel b) {
    b.setBackground(new Color(94, 112, 107));
  }

  void resetcolor(JLabel b) {
    b.setBackground(Color.black);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("dark metal".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new StartFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Main;
  private javax.swing.JPanel actionButton;
  private javax.swing.JLabel lblFastFood;
  private javax.swing.JLabel lblLogo;
  private javax.swing.JLabel orderButton;
  // End of variables declaration//GEN-END:variables
}
